//
// Created by User on 2025/01/24.
//

#ifndef COMITTONXX_COMMON_H
#define COMITTONXX_COMMON_H

typedef u_int32_t   LONG;
typedef	u_int16_t	WORD;
typedef	u_int8_t	BYTE;

#define ERROR_CODE_MALLOC_FAILURE -1001
#define ERROR_CODE_CACHE_COUNT_LIMIT_EXCEEDED -1002
#define ERROR_CODE_CACHE_INDEX_OUT_OF_RANGE -1003
#define ERROR_CODE_CACHE_NOT_INITIALIZED -1004
#define ERROR_CODE_CACHE_IS_FULL -1005
#define ERROR_CODE_IMAGE_TYPE_NOT_SUPPORT -1006
#define ERROR_CODE_USER_CANCELED -1007

#endif //COMITTONXX_COMMON_H
